### ISSUE TITLE
V1: Initial Launch

### ISSUE THREAD

**Issue by thalida** [thalida/homely#9]
## Tasks
- [x] Modules (Widgets)
  - [x] Link
  - [x] Text (with markdown support)
  - [x] Images (link maybe with unsplash)
  - [x] Live Weather (Window, Icons)
  - [x] Date Time (with international support)
- [x] Widget Layouts 
  - [x] Link (icon, flag, card)
  - [x] Text (global fonts)
  - [x] Live Weather (text, image only, window)
  - [x] Date Time (text based, color gradient)
  - [x] Images (cover, contain, position)
- [x] Widget Styles 
  - [x] Link
  - [x] Text
  - [x] Live Weather
  - [x] Date Time
  - [x] Images
- [ ] Widget Menus 
  - [ ] Link
  - [ ] Text
  - [ ] Live Weather
  - [ ] Date Time
  - [ ] Images
- [x] Theming
  - [x] Light & Dark Mode
  - [x] Predefined color sets (red, orange, yellow, etc.)
  - [x] Set backgrounds on all cards
  - [x] Page background color
  - [x] Sidebar
- [x] Import & Export Dashboard
- [x] Edit Mode
  - [x] Positioning (z-index - move to foward/backward etc)
  - [x] Drag/Paste to create module (link/image/video)
  - [x] grid
  - [x] responsive grid
  - [x] don't cover grid on open
- [x] API
  - [x] Cache metadata fetching
- [ ] Tests
  - [ ] Link
  - [ ] Text
  - [ ] Live Weather
  - [ ] Date Time
  - [ ] Images
  - [ ] Auth
- [ ] Render Setup
- [ ] Arc Reddit Post
- [ ] Product Hunt Launch
- [x] Landing page
- [x] Auth Flows
- [x] Share URL
- [x] Create & Switch Between Spaces
